# Generated by Django 2.2.2 on 2021-07-26 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auther_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('name', models.CharField(default='', max_length=100, verbose_name='User Name')),
                ('m_no', models.PositiveIntegerField(default=0, verbose_name='Mobile no')),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(default='', max_length=100, verbose_name='User Name')),
                ('cust_m_no', models.PositiveIntegerField(default=0, verbose_name='Mobile no')),
                ('cust_email', models.CharField(default='', max_length=100)),
                ('cust_password', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('sub', models.TextField(default='', max_length=100)),
                ('mess', models.TextField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(default='', max_length=100, verbose_name='Image Name')),
                ('pro_price', models.PositiveIntegerField(default=0, verbose_name='Image Price')),
                ('pro_image', models.ImageField(blank=True, upload_to='images/')),
                ('pro_detail', models.CharField(default='', max_length=200)),
                ('auther', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.Auther_Class')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(default='', max_length=100)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('pro_price', models.PositiveIntegerField(default=0)),
                ('name', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.Customer_Class')),
            ],
        ),
    ]
